name: DefineAPI
main: defineoutside.main.MainAPI
version: 1.0
load: STARTUP
api-version: 1.15
depend: [ProtocolLib]
commands:
  debugmg:
    description: Pls no touch
  debugworld:
    description: No touch this either
  whatgame:
    description: WHERE AM I
  hub:
    description: Life is an illusion.
  lobby:
    description: Life is definitely an illusion
  leave:
    description: Is death an illusion?
  reloadconfigs:
    description: Do not run this command
  setuuid:
    description: DO NOT RUN THIS COMMAND
  getuuid:
    description: Okay, fine, you can run this meaningless command
  joinqueue:
    description: Usage - /Joinqueue Bedwars
  setgametype:
    description: Types are lobby, gamelobby, and bedwars
  setgamemode:
    description: Sets the gamemode (you're welcome)
  getgamemode:
    description: What gamemode is this?
  whatteam:
    description: What team is this?
  shutdownforupdate:
    description: Updates the server